import Challenge
set_option pp.all true
set_option maxHeartbeats 1000000
#check @HadamardBFormal.theoremA
#check @HadamardBFormal.theoremA_sufficiency
#check @HadamardBFormal.theoremB_profile
#check @HadamardBFormal.D5
#check @HadamardBFormal.D6
#check @HadamardBFormal.goethalsSeidel_abelian
#check @HadamardBFormal.borderedGS_index_one
#check @HadamardBFormal.lemmaT
#check @HadamardBFormal.twist_profile_iff
#check @HadamardBFormal.twist_isConjugation
#check @HadamardBFormal.twist_isHadamard_iff
#check @HadamardBFormal.theoremD_tables
#check @HadamardBFormal.theoremD_rowTable
#check @HadamardBFormal.theoremD_border
#check @HadamardBFormal.deltaSqSum_eq_four
#check @HadamardBFormal.theoremD_transport
#check @HadamardBFormal.theoremD_transport_converse
#check @HadamardBFormal.theoremD_transport_iff
#check @HadamardBFormal.theoremD_degenerate_collapse
#check @HadamardBFormal.theoremD_degenerate_converse
#check @HadamardBFormal.collapse_seedProblem_bijection
#check @HadamardBFormal.hadamard_52_bordered
#check @HadamardBFormal.hadamardExists_52
#check @HadamardBFormal.hadamard_20_bordered
#check @HadamardBFormal.hadamardExists_20
#check @HadamardBFormal.gate52_columnTable
