/-
This file is generated by scripts/export_data.py. Do not edit it by hand.
The absolute --source-root is intentionally omitted so identical pinned inputs
produce identical output on every machine.

Pinned sources:
* Hadamard-B/data/h52-gate.json
  SHA-256: ef60c4ff9f245eec5ba7f035e5968152836207fcd9235a0b1851150d2fb1d170
* Hadamard-B/data/h20-boundary.json
  SHA-256: 716610543b79ab9e1c9f1adb142c114544e70e58d370500130b83c17a18cf254

The records additionally carry their own provenance digests, which are the
lab's pins on the parameter blocks rather than on this file:
* h52-gate.json, record.pinned_sha256
  e2c3e48b0fc65f5283e833096824b4fec651d8c57694ae45b3842c23c87ad7ca
* h20-boundary.json, instance T1, pinned_sha256
  50eecc761e12b76944b301b7aaeb03a61cb6b88cfc52c67caaacf20eef0e6c9b
-/

import Mathlib.Data.ZMod.Basic
import HadamardBFormal.Defs

/-!
# Two bordered Goethals--Seidel instances, as Lean data

* the Theorem-D gate of `NOTE-B` §2.2 (cert 03): a from-scratch
  `s = 1, i = 2` instance on the non-cyclic group
  `G = ZMod 2 x ZMod 2 x ZMod 3`, in the `ε = +1` branch (`κ ρ = 0`);
* the `w = 2s` hypothesis-boundary instance T1 of `NOTE-B` §2.2 (cert 05),
  on `G = ZMod 2 x ZMod 2` with `K` the **diagonal** subgroup — an
  arbitrary index-two subgroup rather than a coordinate kernel, which the
  surjective-hom model handles as `κ(a,b) = a + b`.

The companion instance T2 of the order-20 record is **out of scope by
construction**: it declares the transpose-negated orientation, and this
library formalizes the standard orientation only.  The exporter refuses to
emit it.

Only the literals and the index maps live here.  Every mathematical
property of this data is checked by kernel reduction in
`HadamardBFormal/Data.lean`, and the Hadamard conclusions are derived from
Theorem A in `HadamardBFormal/Results.lean`.
-/

namespace HadamardBFormal.Data

open HadamardBFormal

/-- The gate group `G = ZMod 2 x ZMod 2 x ZMod 3`, of order 12. -/
abbrev G52 : Type := ZMod 2 × ZMod 2 × ZMod 3

/-- The flat index of a group element, in the row-major mixed-radix order of
`Hadamard-B/tools/bordered_gs.py` (`AbelianGroup.idx`): `(a,b,c) ↦ 6a + 3b + c`. -/
def gidx52 (z : G52) : Fin 12 :=
  ⟨6 * z.1.val + 3 * z.2.1.val + z.2.2.val, by
    have h0 : z.1.val < 2 := ZMod.val_lt z.1
    have h1 : z.2.1.val < 2 := ZMod.val_lt z.2.1
    have h2 : z.2.2.val < 3 := ZMod.val_lt z.2.2
    omega⟩

/-- The flat index of a border-table column `(J, b)`, class index fastest:
`(J, b) ↦ 2J + b`. -/
def pairIdx (z : Fin 4 × ZMod 2) : Fin 8 :=
  ⟨2 * z.1.val + z.2.val, by
    have h0 : z.1.val < 4 := z.1.isLt
    have h1 : z.2.val < 2 := ZMod.val_lt z.2
    omega⟩

/-- The index-two character of `G`, `coset_divisors = [2,1,1]`: the first
coordinate. -/
def kappa52 : G52 →+ ZMod 2 where
  toFun z := z.1
  map_zero' := rfl
  map_add' _ _ := rfl

@[simp]
theorem kappa52_apply (z : G52) : kappa52 z = z.1 := rfl

/-- The reflection shift `ρ`, the record's `r_shift = (0,0,0)`.  Since `κ ρ = 0`
this instance is the `ε = +1` branch. -/
def rho52 : G52 := 0

private def seed52Data : Vector (Vector Int 12) 4 :=
  #v[
    #v[
      -1, -1, 1, 1, 1, -1, -1, 1, -1, 1, -1, -1
    ],
    #v[
      -1, -1, 1, -1, -1, 1, 1, 1, -1, -1, -1, -1
    ],
    #v[
      1, -1, -1, 1, -1, -1, 1, 1, -1, -1, -1, -1
    ],
    #v[
      -1, 1, -1, 1, -1, -1, 1, 1, -1, -1, -1, -1
    ]
  ]

/-- The four seed sequences of the gate record, as functions on `G`. -/
def seed52 : Fin 4 → G52 → ℤ := fun q g => (seed52Data.get q).get (gidx52 g)

private def corner52Data : Vector (Vector Int 4) 4 :=
  #v[
    #v[
      -1, -1, -1, 1
    ],
    #v[
      -1, -1, 1, -1
    ],
    #v[
      -1, 1, -1, -1
    ],
    #v[
      1, -1, -1, -1
    ]
  ]

/-- The corner `E` of the gate record. -/
def E52 : Matrix (Fin (4 * 1)) (Fin (4 * 1)) ℤ :=
  fun r c => (corner52Data.get r).get c

private def rowTable52Data : Vector (Vector Int 8) 4 :=
  #v[
    #v[
      -1, 1, 1, -1, 1, -1, -1, 1
    ],
    #v[
      1, -1, -1, 1, 1, -1, -1, 1
    ],
    #v[
      1, -1, 1, -1, -1, 1, -1, 1
    ],
    #v[
      -1, 1, -1, 1, -1, 1, -1, 1
    ]
  ]

/-- The row table `P` of the gate record, indexed by `Fin 4 × ZMod 2`. -/
def P52 : Matrix (Fin (4 * 1)) (Fin 4 × ZMod 2) ℤ :=
  fun r z => (rowTable52Data.get r).get (pairIdx z)

private def colTable52Data : Vector (Vector Int 8) 4 :=
  #v[
    #v[
      1, -1, 1, -1, 1, -1, -1, 1
    ],
    #v[
      -1, 1, -1, 1, 1, -1, -1, 1
    ],
    #v[
      -1, 1, 1, -1, -1, 1, -1, 1
    ],
    #v[
      1, -1, -1, 1, -1, 1, -1, 1
    ]
  ]

/-- The column table `Q` of the gate record.  The record stores it transposed:
`Q[(I,b)][r] = col_table[r][2I + b]`. -/
def Q52 : Matrix (Fin 4 × ZMod 2) (Fin (4 * 1)) ℤ :=
  fun z c => (colTable52Data.get c).get (pairIdx z)

/-! ### The order-20 boundary instance T1 -/

/-- The boundary group `G = ZMod 2 x ZMod 2`, of order 4. -/
abbrev G20 : Type := ZMod 2 × ZMod 2

/-- The flat index of a group element, row-major mixed radix: `(a,b) ↦ 2a + b`. -/
def gidx20 (z : G20) : Fin 4 :=
  ⟨2 * z.1.val + z.2.val, by
    have h0 : z.1.val < 2 := ZMod.val_lt z.1
    have h1 : z.2.val < 2 := ZMod.val_lt z.2
    omega⟩

/-- The **diagonal** index-two subgroup `K = ⟨(1,1)⟩`, presented as the
surjective hom `κ(a,b) = a + b`.  This is not a coordinate kernel, which is
exactly the point of the boundary record. -/
def kappa20 : G20 →+ ZMod 2 where
  toFun z := z.1 + z.2
  map_zero' := rfl
  map_add' a b := add_add_add_comm a.1 b.1 a.2 b.2

@[simp]
theorem kappa20_apply (z : G20) : kappa20 z = z.1 + z.2 := rfl

/-- The reflection shift `ρ = (1,1)` of the boundary record.  Note `κ ρ = 0`. -/
def rho20 : G20 := (1, 1)

private def seed20Data : Vector (Vector Int 4) 4 :=
  #v[
    #v[
      -1, -1, 1, 1
    ],
    #v[
      -1, 1, -1, 1
    ],
    #v[
      1, -1, -1, -1
    ],
    #v[
      -1, -1, -1, -1
    ]
  ]

/-- The four seed sequences of the boundary record. -/
def seed20 : Fin 4 → G20 → ℤ := fun q g => (seed20Data.get q).get (gidx20 g)

private def corner20Data : Vector (Vector Int 4) 4 :=
  #v[
    #v[
      -1, -1, -1, -1
    ],
    #v[
      1, 1, -1, -1
    ],
    #v[
      1, -1, 1, -1
    ],
    #v[
      -1, 1, 1, -1
    ]
  ]

/-- The corner `E` of the boundary record. -/
def E20 : Matrix (Fin (4 * 1)) (Fin (4 * 1)) ℤ :=
  fun r c => (corner20Data.get r).get c

private def rowTable20Data : Vector (Vector Int 8) 4 :=
  #v[
    #v[
      -1, 1, 1, -1, -1, 1, 1, -1
    ],
    #v[
      1, -1, 1, -1, -1, 1, -1, 1
    ],
    #v[
      1, -1, -1, 1, -1, 1, 1, -1
    ],
    #v[
      1, -1, 1, -1, 1, -1, 1, -1
    ]
  ]

/-- The row table `P` of the boundary record. -/
def P20 : Matrix (Fin (4 * 1)) (Fin 4 × ZMod 2) ℤ :=
  fun r z => (rowTable20Data.get r).get (pairIdx z)

private def colRows20Data : Vector (Vector Int 4) 8 :=
  #v[
    #v[
      1, -1, -1, -1
    ],
    #v[
      -1, 1, 1, 1
    ],
    #v[
      -1, -1, 1, -1
    ],
    #v[
      1, 1, -1, 1
    ],
    #v[
      1, 1, 1, -1
    ],
    #v[
      -1, -1, -1, 1
    ],
    #v[
      1, -1, 1, 1
    ],
    #v[
      -1, 1, -1, -1
    ]
  ]

/-- The column table `Q` of the boundary record.  This record stores `Q` row by
row — `Q[(I,b)][r] = col_rows[2I + b][r]` — not transposed. -/
def Q20 : Matrix (Fin 4 × ZMod 2) (Fin (4 * 1)) ℤ :=
  fun z c => (colRows20Data.get (pairIdx z)).get c

end HadamardBFormal.Data
